pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){ //cache files directories & running tests
                    sh 'export GOCACHE=/tmp/go-cache && export GOMODCACHE=/tmp/go-mod-cache && go test -v ./...'
                }
            }
        }

        stage('Unit Tests - Frontend'){
            agent {
                docker {
                    imae 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontedn'{
                    sh '''
                    npm ci 
                    npm test
                    '''
                })
            }

        }
    }
}