pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){ //cache files directories & running tests & creating a junit report
                    sh 'export GOCACHE=/tmp/go-cache && export GOMODCACHE=/tmp/go-mod-cache && go test -v ./... 2>&1 | go-junit-report > test-results.xml'
                }
            }
            //adding "post" step that shall be executed after all the steps ()
            post {
                always {//always added to be executed each time, regardless if the tests fail or success
                    junit 'bugtracker-backend/test-results.xml'//adding the report file dir
                }
            }
        }

        stage('Unit Tests - Frontend'){
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend'){
                    sh '''
                    npm ci 
                    npm test
                    '''
                }
            }
            //adding "post" step that shall be executed after all the steps ()
            post {
                always {//always added to be executed each time, regardless if the tests fail or success
                    junit 'bugtracker-frontend/test-results.xml' //adding the report file dir
                }
            }
        }
    }
}