name: CI

on:
    push:                               #everytime a change is pushed to the main branch
        branches:
            - main
    workflow_dispatch:                  #possibility to run it directly via UI

jobs: #specifying the job
    unit-tests-backend:
        runs-on: ubuntu-latest
        steps:                               #job steps
            - uses: actions/checkout@v4      #checking out the sourcecode

            #at first we need to install "go" to be able to run the BE tests
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: "1.21"
                cache-dependency-path: bugtracker-backend/go.sum

            - name: Install go-junit-report    #installin ght go-junit-report in order to create & publish the report
              run: go install github.com/jstemmer/go-junit-report/v2@latest

            - name: Execute Backend Unit Tests       #executing the BE tests
              working-directory: ./bugtracker-backend
              run: |
                go test -v ./... 2>&1 | go-junit-report > test-results.xml   
                
            - name: Publish Backend Unit tests Report      #publishng the BE Unit Tests Report
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: Backend Unit Tests Report
                path: bugtracker-backend/test-results.xml
                reporter: jest-junit    
    
    unit-tests-frontend:               #running the frontend-unit tests  
        needs: unit-tests-backend      #the backend tests needs to be finished first 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js     #setting up Nodejs & cache
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache-dependency-path: bugtracker-frontend/package-lock.json

            - name: Execute Frontend Unit Tests
              working-directory: ./bugtracker-frontend
              run: |
                npm ci
                npm test

            - name: Publish Frontend Unit Tests Report        # step to publishing the FE Unit Test Report
              uses: dorny/test-reporter@v1                    #testReporter
              if: always()                              
              with:
                name: Frontend Unit Tests Report              #reportName
                path: bugtracker-frontend/test-results.xml
                reporter: jest-junit                          #reporterType







            
